/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawpals;

import javax.swing.SwingConstants; 
/**
 *
 * @author Syakira
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    private String currentIdAdopter;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(String idAdopter) {
        initComponents();
        this.currentIdAdopter = idAdopter;
        
        lblIcon.setHorizontalTextPosition(SwingConstants.LEFT);
        lblIcon.setVerticalTextPosition(SwingConstants.CENTER);
        lblIcon.setIconTextGap(12); 
        lblIcon.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        
        aksiNavigasi();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblDashBoard = new javax.swing.JLabel();
        lblTsc = new javax.swing.JLabel();
        lblPetList = new javax.swing.JLabel();
        imgLog = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/5.png"))); // NOI18N
        lblIcon.setText("Profile");
        jPanel1.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 190, -1));

        lblDashBoard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDashBoard.setForeground(new java.awt.Color(0, 0, 255));
        lblDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/j.png"))); // NOI18N
        lblDashBoard.setText("Dashboard");
        jPanel1.add(lblDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 180, 50));

        lblTsc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/i.png"))); // NOI18N
        lblTsc.setText("Transaction");
        jPanel1.add(lblTsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 210, 70));

        lblPetList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPetList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/3.png"))); // NOI18N
        lblPetList.setText("Pet list ");
        jPanel1.add(lblPetList, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 170, 50));

        imgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/log.png"))); // NOI18N
        jPanel1.add(imgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 58)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PawPals");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 270, 160));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/image.png"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aksiNavigasi() {
        lblPetList.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        lblPetList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new PetList(currentIdAdopter).setVisible(true);
                dispose();
            }
        });

        lblTsc.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        lblTsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new Transaction(currentIdAdopter, 0, "").setVisible(true);
                dispose();
            }
        });
        
        imgLog.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        imgLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new LoginUser().setVisible(true);
                dispose();
            }
        });
        
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                //javax.swing.JOptionPane.showMessageDialog(null, "Membuka profile ID: " + currentIdAdopter);
                new Profile(currentIdAdopter).setVisible(true);
            }
        });
    }       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel imgLog;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDashBoard;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPetList;
    private javax.swing.JLabel lblTsc;
    // End of variables declaration//GEN-END:variables
}
