/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawpals;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Syakira
 */
public class Kelola extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kelola.class.getName());

    /**
     * Creates new form Kelola
     */

    public Kelola() {
   initComponents();
    loadData();
    
    txtIdHewan.setEditable(true); 
txtIdHewan.setEnabled(true);  
txtIdHewan.setFocusable(true); 

// Untuk Nama Peliharaan
txtPemeliharaan.setEnabled(true);
txtPemeliharaan.setFocusable(true);

// Untuk Nama Pemilik
txtPemilik.setEnabled(true);
txtPemilik.setFocusable(true);

// Untuk Status Kesehatan
txtStatus.setEnabled(true);
txtStatus.setFocusable(true);

// Untuk Umur
txtUmur.setEnabled(true);
txtUmur.setFocusable(true);
txtUmur.setRequestFocusEnabled(true);
tblHewan.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblHewan.getSelectedRow();
        if (row != -1) {
    
            txtPemeliharaan.setText(tblHewan.getValueAt(row, 0).toString());
            txtUmur.setText(tblHewan.getValueAt(row, 1).toString());
            txtStatus.setText(tblHewan.getValueAt(row, 3).toString());
        }
    }
});
    // Tambahkan ini agar field bisa diedit
    txtIdHewan.setEnabled(false );
    txtPemeliharaan.setEnabled(true);
    txtUmur.setEnabled(true);
    txtPemilik.setEnabled(true);
    txtStatus.setEnabled(true);
}

private void loadData() {
DefaultTableModel model = (DefaultTableModel) tblHewan.getModel();
    model.setRowCount(0);
    try {
        String sql = "SELECT * FROM hewan";
        Statement st = Koneksi.getKoneksi().createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nama_hewan"),      // Sesuai DB
                rs.getInt("umur"),               // Sesuai DB
                rs.getString("jenis"),           // Sesuai DB
                rs.getString("kondisi_kesehatan") // Sesuai DB
            });
        }
    } catch (Exception e) {
        System.out.println("Error load data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDasboard = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtProfile = new javax.swing.JLabel();
        txtKelola = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        txtIdHewan = new javax.swing.JTextField();
        txtPemeliharaan = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHewan = new javax.swing.JTable();
        imgLog = new javax.swing.JLabel();
        txtPemilik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        jLabel4.setText("PawPals");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 70));

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/1.png"))); // NOI18N
        jPanel1.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/PAWPALS.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 0, 486, 139));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel7.setText("Kelola Data Peliharaan ( Pet List )");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("ID Hewan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Umur ( Bulan )");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Nama Peliharaan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, 38));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Nama Pemilik");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Jenis Hewan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Status Kesehatan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        cbJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Kucing", "Anjing" }));
        cbJenis.addActionListener(this::cbJenisActionPerformed);
        jPanel1.add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 180, -1));

        btnTambah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, -1, -1));

        btnUbah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, -1, -1));

        btnHapus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 320, -1, -1));

        btnClear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtDasboard.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtDasboard.setText("Dashboard");
        txtDasboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDasboardMouseClicked(evt);
            }
        });

        txtTransaksi.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtTransaksi.setText("Transaksi");
        txtTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTransaksiMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/ajg.png"))); // NOI18N

        txtProfile.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtProfile.setText("Profile Akun");
        txtProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProfileMouseClicked(evt);
            }
        });

        txtKelola.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        txtKelola.setText("Kelola Peliharaan");
        txtKelola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKelolaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKelola)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtProfile)
                                .addComponent(txtDasboard))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(txtDasboard)
                .addGap(18, 18, 18)
                .addComponent(txtProfile)
                .addGap(18, 18, 18)
                .addComponent(txtKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTransaksi)
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 820));

        txtUmur.setAutoscrolls(false);
        txtUmur.setRequestFocusEnabled(false);
        txtUmur.setVerifyInputWhenFocusTarget(false);
        txtUmur.addActionListener(this::txtUmurActionPerformed);
        jPanel1.add(txtUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 180, 30));

        txtIdHewan.setEditable(false);
        txtIdHewan.setAutoscrolls(false);
        txtIdHewan.setEnabled(false);
        txtIdHewan.setFocusable(false);
        txtIdHewan.setRequestFocusEnabled(false);
        txtIdHewan.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txtIdHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 194, 180, 30));

        txtPemeliharaan.setAutoscrolls(false);
        txtPemeliharaan.setFocusable(false);
        txtPemeliharaan.setRequestFocusEnabled(false);
        txtPemeliharaan.setVerifyInputWhenFocusTarget(false);
        txtPemeliharaan.addActionListener(this::txtPemeliharaanActionPerformed);
        txtPemeliharaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPemeliharaanKeyPressed(evt);
            }
        });
        jPanel1.add(txtPemeliharaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 180, 30));

        txtStatus.setAutoscrolls(false);
        txtStatus.setFocusable(false);
        txtStatus.setRequestFocusEnabled(false);
        txtStatus.setVerifyInputWhenFocusTarget(false);
        txtStatus.addActionListener(this::txtStatusActionPerformed);
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 180, 30));

        tblHewan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Hewan", "Umur", "Jenis Kelamin", "Riwayat Kesehatan"
            }
        ));
        tblHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHewanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHewan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 920, 320));

        imgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/log.png"))); // NOI18N
        jPanel1.add(imgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 680, -1, -1));

        txtPemilik.setAutoscrolls(false);
        txtPemilik.setFocusable(false);
        txtPemilik.setRequestFocusEnabled(false);
        txtPemilik.setVerifyInputWhenFocusTarget(false);
        txtPemilik.addActionListener(this::txtPemilikActionPerformed);
        jPanel1.add(txtPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
try {
        // Sesuaikan nama kolom dengan struktur database (nama_hewan, jenis, umur, kondisi_kesehatan)
        String sql = "INSERT INTO hewan (nama_hewan, jenis, umur, kondisi_kesehatan) VALUES (?, ?, ?, ?)";
        PreparedStatement ps = Koneksi.getKoneksi().prepareStatement(sql);
        
        ps.setString(1, txtPemeliharaan.getText()); // Nama Peliharaan
        ps.setString(2, cbJenis.getSelectedItem().toString()); // Jenis (Kucing/Anjing)
        ps.setInt(3, Integer.parseInt(txtUmur.getText())); // Umur
        ps.setString(4, txtStatus.getText()); // Kondisi Kesehatan
        
        ps.executeUpdate();
        loadData(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambah!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "UPDATE hewan SET nama_peliharaan=?, jenis_hewan=?, umur=?, nama_pemilik=?, status_kesehatan=? WHERE id_hewan=?";
        java.sql.PreparedStatement ps = Koneksi.getKoneksi().prepareStatement(sql);
        ps.setString(1, txtPemeliharaan.getText());
        ps.setString(2, cbJenis.getSelectedItem().toString());
        ps.setString(3, txtUmur.getText());
        ps.setString(4, txtPemilik.getText());
        ps.setString(5, txtStatus.getText());
        ps.setString(6, txtIdHewan.getText()); 
        ps.executeUpdate();
        loadData();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal ubah: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtIdHewan.setText("");
    txtPemeliharaan.setText("");
    txtUmur.setText("");
    txtPemilik.setText("");
    txtStatus.setText("");
    cbJenis.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed
  
    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPemilikActionPerformed

    private void txtPemeliharaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemeliharaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPemeliharaanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:                                       
    if (txtIdHewan.getText().equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus!");
        return;
    }

    int ok = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (ok == 0) {
        try {
            String sql = "DELETE FROM hewan WHERE id_hewan=?";
            java.sql.PreparedStatement ps = Koneksi.getKoneksi().prepareStatement(sql);
            ps.setString(1, txtIdHewan.getText());
            ps.executeUpdate();
            
            loadData();
            btnClearActionPerformed(evt);
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        } 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtDasboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDasboardMouseClicked
        // TODO add your handling code here:
    Dashboard dashboard = new Dashboard();
    dashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_txtDasboardMouseClicked

    private void txtProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProfileMouseClicked
        // TODO add your handling code here:
               Profile pf = new Profile();
    pf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_txtProfileMouseClicked

    private void txtTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTransaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiMouseClicked

    private void txtKelolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKelolaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKelolaMouseClicked

    private void txtPemeliharaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPemeliharaanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPemeliharaanKeyPressed

    private void tblHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHewanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHewanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kelola().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel imgLog;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHewan;
    private javax.swing.JLabel txtDasboard;
    private javax.swing.JTextField txtIdHewan;
    private javax.swing.JLabel txtKelola;
    private javax.swing.JTextField txtPemeliharaan;
    private javax.swing.JTextField txtPemilik;
    private javax.swing.JLabel txtProfile;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JLabel txtTransaksi;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
