/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawpals;

import javax.swing.SwingConstants;

/**
 *
 * @author Syakira
 */
public class PetList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PetList.class.getName());

    private String currentIdAdopter;
    /**
     * Creates new form PetList
     */
    public PetList(String idAdopter) {
        initComponents();
        this.currentIdAdopter = idAdopter;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        
        lblIcon.setHorizontalTextPosition(SwingConstants.LEFT);
        lblIcon.setVerticalTextPosition(SwingConstants.CENTER);
        lblIcon.setIconTextGap(12); 
        lblIcon.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        
        aksiNavigasi();
        cariDanFilterHewan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDb = new javax.swing.JLabel();
        lblPetList = new javax.swing.JLabel();
        lblTsc = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbJenis1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHewan = new javax.swing.JTable();
        imgLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/j.png"))); // NOI18N
        lblDb.setText("Dashboard");
        jPanel1.add(lblDb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 180, 50));

        lblPetList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPetList.setForeground(new java.awt.Color(0, 0, 255));
        lblPetList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/3.png"))); // NOI18N
        lblPetList.setText("Pet list ");
        jPanel1.add(lblPetList, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 170, 50));

        lblTsc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/i.png"))); // NOI18N
        lblTsc.setText("Transaction");
        jPanel1.add(lblTsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 210, 70));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, -1, -1));

        lblIcon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/5.png"))); // NOI18N
        lblIcon.setText("Profile");
        jPanel1.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 190, -1));

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("PawPals");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Status");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, -1));

        txtCari.addActionListener(this::txtCariActionPerformed);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cari Hewan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Diadopsi", "Sudah Diadopsi" }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);
        jPanel1.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Jenis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        cbJenis1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Kucing", "Anjing" }));
        cbJenis1.addActionListener(this::cbJenis1ActionPerformed);
        jPanel1.add(cbJenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 160, 30));

        tblHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "Nama Hewan", "Jenis Kelamin", "Umur", "Status", "Riwayat Kesehata"
            }
        ));
        jScrollPane1.setViewportView(tblHewan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 1150, 370));

        imgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/log.png"))); // NOI18N
        jPanel1.add(imgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
        cariDanFilterHewan();
    }//GEN-LAST:event_txtCariActionPerformed

    private void cbJenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenis1ActionPerformed
        // TODO add your handling code here:
        cariDanFilterHewan();
    }//GEN-LAST:event_cbJenis1ActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
        cariDanFilterHewan();
    }//GEN-LAST:event_cbStatusActionPerformed

    private void aksiNavigasi() {
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                javax.swing.JOptionPane.showMessageDialog(null, "Membuka profile ID: " + currentIdAdopter);
            }
        });
        lblDb.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        lblDb.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new Dashboard(currentIdAdopter).setVisible(true);
                dispose();
            }
        });
        
        imgLog.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        imgLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new LoginUser().setVisible(true);
                dispose();
            }
        });
    }
    
    public void cariDanFilterHewan() {
        String kataKunci = txtCari.getText().trim();
        String jenisDipilih = cbJenis1.getSelectedItem().toString();
        String statusDipilih = cbStatus.getSelectedItem().toString();
    
        tblHewan.getColumnModel().getColumn(0).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof javax.swing.Icon) {
                    setIcon((javax.swing.Icon) value);
                    setText("");
                } else {
                    setIcon(null);
                    setText(value != null ? value.toString() : "");
                }
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                if (isSelected) {
                    setBackground(table.getSelectionBackground());
                    setForeground(table.getSelectionForeground());
                } else {
                    setBackground(table.getBackground());
                    setForeground(table.getForeground());
                }
                return this;
            }
        });

        tblHewan.setRowHeight(80);
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Foto", "Nama Hewan", "Jenis Kelamin", "Umur", "Status", "Riwayat Kesehatan" }
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return javax.swing.ImageIcon.class;
                }
                return super.getColumnClass(columnIndex);
            }
        
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblHewan.setModel(model);

        try {
            java.sql.Connection conn = pawpals.Koneksi.getKoneksi();
            StringBuilder sql = new StringBuilder("SELECT foto_hewan, nama_hewan, jenis_kelamin, umur, status_adopsi, kondisi_kesehatan FROM hewan WHERE 1=1");
            java.util.List<Object> params = new java.util.ArrayList<>();
        
            if (!jenisDipilih.equals("Semua")) {
                sql.append(" AND jenis = ?");
                params.add(jenisDipilih);
            }

            if (!statusDipilih.equals("Semua")) {
                sql.append(" AND status_adopsi = ?");
                params.add(statusDipilih);
            }

            if (!kataKunci.isEmpty()) {
                sql.append(" AND (nama_hewan LIKE ? OR kondisi_kesehatan LIKE ? OR jenis_kelamin LIKE ?)");
                String pParam = "%" + kataKunci + "%";
                params.add(pParam);
                params.add(pParam);
                params.add(pParam);
            }
        
            java.sql.PreparedStatement ps = conn.prepareStatement(sql.toString());
            for (int i = 0; i < params.size(); i++) {
                ps.setObject(i + 1, params.get(i));
            }
        
            java.sql.ResultSet rs = ps.executeQuery();
        
            while (rs.next()) {
                String namaFile = rs.getString("foto_hewan");
                javax.swing.ImageIcon imageIcon = null;

                try {
                    java.net.URL imgUrl = getClass().getResource("/pawpals/image/" + namaFile);
                    if (imgUrl != null) {
                        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(imgUrl);
                        java.awt.Image scaledImage = originalIcon.getImage().getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
                        imageIcon = new javax.swing.ImageIcon(scaledImage);
                    }
                } catch (Exception e) {
                    System.out.println("Gagal memuat gambar " + namaFile + ": " + e.getMessage());
                }

                Object[] row = {
                    imageIcon, 
                    rs.getString("nama_hewan"),
                    rs.getString("jenis_kelamin"),
                    rs.getInt("umur") + " Tahun",
                    rs.getString("status_adopsi"),
                    rs.getString("kondisi_kesehatan")
                };
                model.addRow(row);
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Gagal memproses data hewan: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses data: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        //* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PetList("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJenis1;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel imgLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPetList;
    private javax.swing.JLabel lblTsc;
    private javax.swing.JTable tblHewan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
