/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawpals;

/**
 *
 * @author Syakira
 */
public class RegistUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistUser.class.getName());

    /**
     * Creates new form RegistUser
     */
    public RegistUser() {
        initComponents();
        this.setType(java.awt.Window.Type.UTILITY);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUsn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPw = new javax.swing.JPasswordField();
        cbTampil = new javax.swing.JCheckBox();
        btnRegist = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regist User");
        setMaximumSize(new java.awt.Dimension(1280, 720));

        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel5.setText("Create Account");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 58)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PawPals");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/1.png"))); // NOI18N
        jPanel2.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/2.png"))); // NOI18N
        jPanel2.add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, 130));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Already have an account?");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 650, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Full Name");

        txtName.addActionListener(this::txtNameActionPerformed);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Alamat");

        txtAlamat.addActionListener(this::txtAlamatActionPerformed);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("No. Hp");

        txtNoHp.addActionListener(this::txtNoHpActionPerformed);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Username");

        txtUsn.addActionListener(this::txtUsnActionPerformed);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Password");

        txtPw.addActionListener(this::txtPwActionPerformed);

        cbTampil.setText("Tampilkan Password");
        cbTampil.addActionListener(this::cbTampilActionPerformed);

        btnRegist.setText("Register");
        btnRegist.addActionListener(this::btnRegistActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(txtUsn)
                    .addComponent(jLabel6)
                    .addComponent(txtNoHp)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat)
                    .addComponent(jLabel2)
                    .addComponent(txtName)
                    .addComponent(jLabel1)
                    .addComponent(txtPw)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(btnRegist)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbTampil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnRegist)
                        .addGap(23, 23, 23))))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 440, 470));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawpals/image/PawPals (2).jpg"))); // NOI18N
        image1.setText("jLabel1");
        jPanel2.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void txtUsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsnActionPerformed

    private void cbTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTampilActionPerformed
        // TODO add your handling code here:
        if (cbTampil.isSelected()) {
            txtPw.setEchoChar((char) 0); 
        } else {
            txtPw.setEchoChar('*'); 
        }
    }//GEN-LAST:event_cbTampilActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:                               
        LoginUser login = new LoginUser();
        login.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwActionPerformed

    private void btnRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistActionPerformed
        // TODO add your handling code here:
        String nama = txtName.getText().trim();
        String alamat = txtAlamat.getText().trim();
        String noHp = txtNoHp.getText().trim();
        String username = txtUsn.getText().trim(); 
        String password = new String(txtPw.getPassword());

        if (nama.isEmpty() || alamat.isEmpty() || noHp.isEmpty() || username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua data wajib diisi, tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (password.length() != 8) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password harus tepat 8 karakter!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            java.sql.Connection conn = pawpals.Koneksi.getKoneksi();
            String query = "INSERT INTO adopter (nama, alamat, no_hp, username, password) VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, nama);
            ps.setString(2, alamat);
            ps.setString(3, noHp);
            ps.setString(4, username);
            ps.setString(5, password);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Registrasi Berhasil! Akun Adopter PawPals Aktif 🐾", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Pindah otomatis ke halaman login
                LoginUser login = new LoginUser();
                login.setVisible(true);
                this.dispose();
            }

            ps.close();
            conn.close();

        } catch (java.sql.SQLException e) {
            // Mengatasi error jika username yang didaftarkan sudah ada (Error Code 1062 = Duplicate Entry)
            if (e.getErrorCode() == 1062) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username sudah digunakan! Silakan gunakan username lain.", "Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Koneksi Database Gagal: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegist;
    private javax.swing.JCheckBox cbTampil;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUsn;
    // End of variables declaration//GEN-END:variables
}